# Circuits and Programs

In CK the circuit and program functionality are directly available, independently of a PGM. These are exposed to allow researchers to write their own PGM and circuit compilers. Additionally, being familiar with the details of circuits and programs can provide a deeper understanding of CK and its theoretical foundations.

## Overview of Circuits

An arithmetic circuit defines an arithmetic function from input variables (`VarNode` objects)
and constant values (`ConstNode` objects) to one or more result values. Computation is defined
over a mathematical ring, with two operations: addition and multiplication (represented
by `OpNode` objects).

An arithmetic circuit needs to be compiled to a program to execute the function.

Every `ConstNode` has a value (`float`, `int` or `bool`) that is immutable. A `ConstNode`
is identified in a `Circuit` by its value and the values are unique within the circuit.

Every `VarNode` has an index (`idx`) which is a sequence number, starting from zero,
indicating when that `VarNode` was added to its `Circuit`.

A `VarNode` may be temporarily be set to a constant value. This is useful when compiling
a circuit as compilers can make optimisations knowing that certain values are constant.

A `OpNode` represents an arithmetic operation. The arguments of an `OpNode` belong to the
same circuit as the `OpNode`.

All nodes belong to a circuit. All nodes are immutable, with the exception that a
`VarNode` may be temporarily be set to a constant value.


## Overview of Programs

A program represents an arithmetic a function from input values to output values.

A `Program` object wraps a `RawProgram` object which is returned by a circuit compiler. The purpose of
a `Program` is to make calling a `RawProgram` more convenient for interactive use, and it provides
some backwards compatibility with older versions of CK.

A `RawProgram` can also be wrapped by a `ProgramBuffer`, which provides pre-allocated buffers for input, output, and temporary values. `ProgramBuffer` objects are used extensively for PGM queries to enable
efficient and convenient computation.

Every `RawProgram` has a numpy `dtype` which defines the numeric data type for input and output
values. Typically, the `dtype` of a program is a C style double.

Internally, a `RawProgram` delegates to a `RawProgramFunction` which is a `Callable` with the signature:
```
    f(in: Pointer, tmp: Pointer, out: Pointer) -> None
```

The three arguments are `ctypes` pointers to arrays of the specified `dtype`. The arguments are
(1) input values, (2) temporary working memory, and (3) output values.
A `RawProgram` records the required sizes for the arguments and records the mapping from the
input parameters to the circuit variables (as provided to the circuit compiler).

A `RawProgramFunction` is expected to place result in the output array (argument 3) and not write
to the input array (argument 1). The memory provided by argument 2 can be used at the function's
discretion.

Note that use of `RawProgram` and `Program` functions are thread-safe. However, a `ProgramBuffer` object
is not thread-safe due to the buffers that are pre-allocated and reused by the object.


## Circuits

Here we create a simple demonstration circuit representing the expression: $x0 * x1 + 123$.

In [1]:
from ck.circuit import Circuit

cct = Circuit()

x0 = cct.new_var()  # this var will have index 0
x1 = cct.new_var()  # this var will have index 1
c123 = cct.const(123)
m = cct.mul(x0, x1)
a = cct.add(c123, m)

Every circuit variable has an index, starting from zero and counting in the order that the variables were created.

In [2]:
print(x0.idx, x1.idx)

0 1


Circuit variables can be accessed from the circuit by their index.

In [3]:
cct.vars[0]

In [4]:
x0 == cct.vars[0]

True

In [5]:
x0 == cct.vars[1]

False

A circuit's details can be dumped to a human-readable form.

Op nodes are printed in the form: {operation}<{ref-number}>: {arguments}

Var nodes are printed in the form: var[\{idx\}]

Const nodes are printed merely as constant values.


In [6]:
cct.dump()

number of vars: 2
number of const nodes: 3
number of op nodes: 2
number of operations: 2
number of arcs: 4
var nodes: 2
op nodes: 2 (arcs: 4, ops: 2)
  mul<0>: var[0] var[1]
  add<1>: 123 mul<0>


## Programs

A circuit can be compiled to a program by using a `CircuitCompiler`. A default circuit compiler is
available as `ck.circuit_compiler.DEFAULT_CIRCUIT_COMPILER`. A circuit compiler
takes a collection of `CircuitNode` objects and returns a `RawProgram` to calculate the values of the given circuit nodes.

The following example compiles the circuit above.

In [7]:
from ck.circuit_compiler import DEFAULT_CIRCUIT_COMPILER
from ck.program import RawProgram


raw_program: RawProgram = DEFAULT_CIRCUIT_COMPILER(a)  # `a` is the top "addition" node of the circuit.

Every program has a numpy `dtype` which defines the numeric data type for input and output values.

In this case, the default type was used, which is a C style double.

In [8]:
raw_program.dtype

numpy.float64

The raw program is a function from an input array to an output array.

In [9]:
print(raw_program([0, 1]))

[123.]


A raw program is typically referenced and used by other objects. For example a raw program can be wrapped in a `ProgramBuffer` which provides pre-allocated buffers for input, output, and temporary values for more efficient and convenient computations.

In [10]:
from ck.program import ProgramBuffer

program = ProgramBuffer(raw_program)

program[0] = 123   # set the first program argument
program[1] = 456   # set the second program argument


print(program[0], program[1])


123.0 456.0


The result of a program buffer is obtained by calling `compute`.

In [11]:
program.compute()

array([56211.])

The last computed results are always available in the results buffer.

In [12]:
program.results

array([56211.])

In general, a program can have multiple results, which is why results are available as a numpy array.

The following example returns two values. These are from circuit nodes `m` and `a`.

In [13]:
program2 = ProgramBuffer(DEFAULT_CIRCUIT_COMPILER(m, a))

In [14]:
program2.number_of_results

2

In [15]:
program2[0] = 30
program2[1] = 50

In [16]:
program2.compute()

array([1500., 1623.])

Whether a program is producing a single result or an array of results, the results are always available as an array, using 'results'.

In [17]:
program.results

array([56211.])

In [18]:
program2.results

array([1500., 1623.])

A program buffer is not thread safe because access to the buffers is unprotected. However, you can easily clone a program buffer which uses the same raw program but different memory allocations for buffers. Consequently, cloned program buffers can be safely set and computed in different threads.

In [19]:
program3 = program2.clone()

program3.compute()

array([1500., 1623.])